version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      POSTGRES_CONN: ${POSTGRES_CONN}
    depends_on:
      - db

volumes:
  db_data: